# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Ctrl-arrow without prefix

# Detect if nvim/vim/vi is running in the current pane
is_nvim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE 'nvim|vim|vi'"

bind -n C-h if-shell "$is_nvim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_nvim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_nvim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_nvim" "send-keys C-l" "select-pane -R"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Use r to reload tmux configuration
unbind r
bind r source-file ~/.tmux.conf
